---
# Simple working solution: Regional Ingresses with shared static IP
# File: playbooks/roles/streaming-server/tasks/deploy-simple-shared-ingress.yml

- name: Get current region from bastion hostname
  shell: "hostname | grep -o 'bastion-[^-]*' | cut -d'-' -f2 || echo 'unknown'"
  register: current_region

- name: Set bastion region fact
  set_fact:
    bastion_region: "{{ current_region.stdout }}"

- name: Create OAuth2 Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: oauth2-proxy
        namespace: "{{ app_namespace }}"
        labels:
          app: oauth2-proxy
          region: "{{ bastion_region }}"
      spec:
        type: LoadBalancer
        selector:
          app: oauth2-proxy
        annotations:
         #cloud.google.com/load-balancer-type: "Internal"
        ports:
          - name: http
            port: 4180
            targetPort: 4180
            protocol: TCP
    wait: true
    wait_timeout: 60

- name: Create regional Ingress with shared IP
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "oauth2-{{ bastion_region }}"
        namespace: "{{ app_namespace }}"
        labels:
          app: oauth2-proxy
          region: "{{ bastion_region }}"
        annotations:
          kubernetes.io/ingress.class: "gce"
          kubernetes.io/ingress.allow-http: "true"
      spec:
        defaultBackend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        rules:
          - http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: oauth2-proxy
                      port:
                        number: 4180
    wait: false

- name: Display deployment status
  debug:
    msg: |
      ✅ Deployed OAuth2 Ingress in region: {{ bastion_region }}
      
      🌐 Configuration:
      - Ingress name: oauth2-{{ bastion_region }}
      - Static IP: {{ project_name }}-global-ip
      - Service: oauth2-proxy:4180
      
      🔄 Google automatically merges all regional Ingresses using the same static IP
      
      ⏱️  Wait 3-5 minutes for load balancer to be ready, then test:
      curl http://{{ load_balancer_ip | default('PENDING') }}/ 

- name: Get Ingress status
  k8s_info:
    api_version: networking.k8s.io/v1
    kind: Ingress
    name: "oauth2-{{ bastion_region }}"
    namespace: "{{ app_namespace }}"
  register: ingress_status

- name: Show Ingress details
  debug:
    msg: |
      📊 Ingress Status for {{ bastion_region }}:
      - Name: {{ ingress_status.resources[0].metadata.name }}
      - IP: {{ ingress_status.resources[0].status.loadBalancer.ingress[0].ip | default('Pending') }}
      - Backend: {{ ingress_status.resources[0].spec.defaultBackend.service.name }}
      
      🔍 Check status: kubectl get ingress oauth2-{{ bastion_region }} -n {{ app_namespace }}