---
# Deploy streaming server components

- name: Create ConfigMap for latency exporter
  k8s:
    state: present
    src: "{{ manifests_dir }}/latency-exporter-config.yaml"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy DaemonSet
  k8s:
    state: present
    src: "{{ manifests_dir }}/daemonset.yaml"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create service
  k8s:
    state: present
    src: "{{ manifests_dir }}/service.yaml"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Wait for DaemonSet rollout if enabled
  shell: kubectl -n {{ app_namespace }} rollout status daemonset/{{ app_name }} --timeout={{ rollout_timeout }}s
  args:
    executable: /bin/bash
  when: wait_for_rollout | bool
  register: rollout_result