---
# Deploy ConfigMap for HLS streaming configuration
# File: playbooks/roles/streaming-server/tasks/deploy-configmap.yml

- name: Generate nginx HLS configuration
  template:
    src: nginx-hls-config.yaml.j2
    dest: "{{ manifests_dir }}/nginx-hls-config.yaml"

- name: Apply nginx HLS ConfigMap
  k8s:
    state: present
    src: "{{ manifests_dir }}/nginx-hls-config.yaml"
    wait: true
    wait_timeout: 60

- name: Generate SSL certificate ConfigMap (self-signed)
  template:
    src: ssl-certs-config.yaml.j2
    dest: "{{ manifests_dir }}/ssl-certs-config.yaml"

- name: Apply SSL certificates ConfigMap
  k8s:
    state: present
    src: "{{ manifests_dir }}/ssl-certs-config.yaml"
    wait: true
    wait_timeout: 60

- name: Verify ConfigMaps creation
  k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ app_namespace }}"
    label_selectors:
      - "app={{ app_name }}"
  register: configmap_status

- name: Display ConfigMap status
  debug:
    msg: "Created {{ configmap_status.resources | length }} ConfigMaps for {{ app_name }}"