---
# Multi-Cluster Ingress for streaming services

- name: Get current region for context
  shell: "hostname | grep -o 'bastion-[^-]*-[^-]*' | cut -d'-' -f2-"
  register: current_region

- name: Set bastion region fact
  set_fact:
    bastion_region: "{{ current_region.stdout }}"

- name: Check if this is the config cluster
  set_fact:
    is_config_cluster: "{{ bastion_region == regions[0] }}"

- name: Create MCI manifests directory
  file:
    path: "{{ manifests_dir }}/mci"
    state: directory
    mode: '0755'

- name: Generate backend service manifest
  template:
    src: mci/backend-config.yaml.j2
    dest: "{{ manifests_dir }}/mci/backend-config.yaml"

- name: Generate streaming service manifest
  template:
    src: mci/streaming-service.yaml.j2
    dest: "{{ manifests_dir }}/mci/streaming-service.yaml"

- name: Apply backend service manifest
  k8s :
    state : present
    src : "{{ manifests_dir }}/mci/backend-config.yaml"
    wait : true
    wait_timeout : 60

- name: Sleep to allow backend service to be ready
  pause:
    seconds: 30

- name: Apply streaming service for MCI
  k8s:
    state: present
    src: "{{ manifests_dir }}/mci/streaming-service.yaml"
    wait: true
    wait_timeout: 60

- name: Sleep to allow backend service to be ready
  pause:
    seconds: 30


- name: Setup MCI resources (Config Cluster Only)
  when: is_config_cluster
  block:
    - name: Generate MultiClusterService manifest
      template:
        src: mci/multicluster-service.yaml.j2
        dest: "{{ manifests_dir }}/mci/multicluster-service.yaml"

    - name: Generate MultiClusterIngress manifest
      template:
        src: mci/multicluster-ingress.yaml.j2
        dest: "{{ manifests_dir }}/mci/multicluster-ingress.yaml"

    - name: Generate ManagedCertificate manifest
      template:
        src: mci/managed-certificate.yaml.j2
        dest: "{{ manifests_dir }}/mci/managed-certificate.yaml"

    - name: Apply MultiClusterService
      k8s:
        state: present
        src: "{{ manifests_dir }}/mci/multicluster-service.yaml"
        wait: true
        wait_timeout: 120

    - name: Apply MultiClusterIngress
      k8s:
        state: present
        src: "{{ manifests_dir }}/mci/multicluster-ingress.yaml"
        wait: false

    - name: Sleep to allow MultiClusterIngress to be ready
      pause:
        seconds: 30

    - name: Apply ManagedCertificate
      k8s:
        state: present
        src: "{{ manifests_dir }}/mci/managed-certificate.yaml"
        wait: false

- name: Display MCI status
  debug:
    msg: |
      ✅ MCI setup completed for region: {{ bastion_region }}
      {% if is_config_cluster %}
      🎯 Config Cluster - Resources deployed
      {% else %}
      📡 Member Cluster - Service registered
      {% endif %}
      🌐 Global URL: https://{{ domain_name }}