---
# Google Cloud SDK installation and configuration tasks

- name: Add Google Cloud SDK apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: Add Google Cloud SDK repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk

- name: Install Google Cloud SDK
  apt:
    name:
      - google-cloud-sdk
      - kubectl
    state: present
    update_cache: yes

- name: Create GCP configuration script
  template:
    src: configure-gcloud.sh.j2
    dest: "/home/{{ admin_username }}/scripts/configure-gcloud.sh"
    mode: '0755'
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"

- name: Create GKE connection script
  template:
    src: connect-to-cluster.sh.j2
    dest: "/home/{{ admin_username }}/scripts/connect-to-cluster.sh"
    mode: '0755'
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"

- name: Install Python packages for K8s
  pip:
    name:
      - kubernetes
      - openshift
      - pyyaml
    state: present