---
# Simplified streaming server deployment

- name: Phase 1 - Setup Admin and Bastion VMs
  hosts: admin,bastions
  become: yes
  tags: ['phase1', 'setup']
  roles:
    - common
    - role: gcloud
      when: inventory_hostname in groups['admin']
    - role: content-manager
      when: inventory_hostname in groups['admin']
    - role: admin-webapp
      when: inventory_hostname in groups['admin']
    - role: bastion
      when: inventory_hostname in groups['bastions']

- name: Phase 2 - Deploy Streaming Application
  hosts: bastions
  become: yes
  tags: ['phase2', 'deploy']
  tasks:
    - name: Create namespace
      k8s:
        name: streaming
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy ConfigMaps
      include_role:
        name: streaming-server
        tasks_from: deploy-configmap

    - name: Deploy streaming server with CSI
      include_role:
        name: streaming-server
        tasks_from: deploy-deployment

    - name: Deploy service
      include_role:
        name: streaming-server
        tasks_from: deploy-service

    - name: Deploy Ingress
      include_role:
        name: streaming-server
        tasks_from: deploy-ingress

#    - name: Deploy NEGs to load balancer
#      include_role:
#        name: streaming-server
#        tasks_from: deploy-negs-to-loadbalancer

- name: Phase 3 - Verification
  hosts: bastion-europe-west2
  become: yes
  tags: ['phase3', 'verify']
  tasks:
    - name: Verify deployment
      include_role:
        name: streaming-server
        tasks_from: verify-deployment