---
# Phase-based Streaming Server Deployment
# Run from external laptop -> admin VM -> bastion hosts

- name: Phase 1a - Prepare Admin VM for K8s Management
  hosts: admin
  become: yes
  gather_facts: yes
  tags: ['phase1', 'setup']
  roles:
    - common
    - gcloud
    - content-manager

- name: Phase 1b - Prepare Bastion VM for K8s Management
  hosts: bastion-asia-southeast1
  become: yes
  gather_facts: yes
  tags: ['phase1', 'setup']
  roles:
    - common
    - bastion


- name: Phase 2 - Deploy Namespace to All Regions
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase2', 'namespace']
  serial: 1  # Deploy one region at a time

  tasks:
    - name: Deploy namespace
      include_role:
        name: streaming-server
        tasks_from: deploy-namespace

- name: Phase 3 - Deploy ConfigMaps to All Regions
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase3', 'configmap']
  serial: 1

  tasks:
    - name: Deploy streaming config
      include_role:
        name: streaming-server
        tasks_from: deploy-configmap

- name: Phase 4 - Deploy HLS Streaming Server DaemonSet
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase4', 'streaming']
  serial: 1

  tasks:
    - name: Deploy streaming daemonset
      include_role:
        name: streaming-server
        tasks_from: deploy-daemonset

- name: Phase 5 - Deploy Services
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase5', 'service']
  serial: 1

  tasks:
    - name: Deploy streaming service
      include_role:
        name: streaming-server
        tasks_from: deploy-service

- name: Phase 6 - Deploy Ingress
  hosts: bastion-asia-southeast1
  become: yes
  gather_facts: yes
  tags: ['phase6', 'ingress']
  serial: 1

  tasks:
    - name: Deploy ingress
      include_role:
        name: streaming-server
        tasks_from: deploy-ingress

- name: Phase 7 - Deploy Monitoring (Optional)
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase7', 'monitoring']
  serial: 1

  tasks:
    - name: Deploy monitoring stack
      include_role:
        name: streaming-server
        tasks_from: deploy-monitoring

- name: Phase 8 - Verification
  hosts: bastion-asia-southeast1 
  become: yes
  gather_facts: yes
  tags: ['phase8', 'verify']

  tasks:
    - name: Verify deployment
      include_role:
        name: streaming-server
        tasks_from: verify-deployment
